- hosts: trystack
  tasks:
    - name: enable epel-release
      become: yes
      yum:
        name: epel-release
        state: latest
    - name: installing packages
      become: yes
      yum: pkg={{item}} state=latest
      with_items:
        - curl
        - python
        - git
        - python-pip
        - ansible
    - name: install docker-py
      become: yes
      shell: pip install 'docker-py>=1.7.0'
      args:
        executable: /bin/bash
    - name: install docker engine
      shell: curl -sSL https://get.docker.com/ | sh
      args:
        executable: /bin/bash 
    - name: enable docker without sudo
      become: yes
      shell: usermod -aG docker centos
      args:
        executable: /bin/bash
    - name: restart docker
      become: yes
      service:
        name: docker
        state: restarted
    - name: copy files
      become: yes
      copy: src={{ item.src }} dest={{ item.dest }}
      with_items:
        - { src: /home/carlo/.ssh/trystack-maior.pem, dest: $HOME/.ssh/trystack-maior.pem }
        - { src: /home/carlo/trystack-ansible/hosts, dest: /etc/ansible/hosts }
        - { src: /home/carlo/trystack-ansible/worker.yml, dest: $HOME/worker.yml }
        - { src: /home/carlo/trystack-ansible/worker.ini, dest: $HOME/worker }
    - name: login on custom docker registry
      become: yes
      docker_login:
        registry_url: https://dockerdemo.ddns.net
        username: demo
        password: demo
        reauthorize: yes
    - name: initialize docker swarm
      become: yes
      shell: docker swarm init
      args:
        executable: /bin/bash
    - name: get worker join token
      become: yes
      command: docker swarm join-token worker -q
      register: join_token
    - name: insert join token in ini file
      ini_file:
        dest: $HOME/worker
        section: docker
        option: join_token
        value: "{{ join_token.stdout }}"
    - name: insert manager ip address in ini file
      ini_file:
        dest: $HOME/worker
        section: docker
        option: manager_ip
        value: "{{ ansible_default_ipv4.address }}"
