- hosts: docker
  gather_facts: False
  pre_tasks:
    - set_fact:
        ubuntu_manager: "{{ lookup('env', 'UBUNTU_MANAGER') }}"
    - name: install-python 2 if ubuntu
      become: yes
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal python-simplejson aptitude)
      when:
        -  (ubuntu_manager == "y")  or (ubuntu_manager == "Y")
    - setup: 
  tasks: 
    - name: Updating...
      become: yes
      apt:
        update_cache: yes
        upgrade: full
      when:
        - ansible_distribution == "Ubuntu"
    - name: Add official ansible repository
      become: yes
      apt_repository:
        repo: 'ppa:ansible/ansible'
      when:
        - ansible_distribution == "Ubuntu"
