- hosts: docker
  gather_facts: False
  pre_tasks:
    - name: install-python 2 if ubuntu
      become: yes
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    - setup: 
  tasks: 
    - name: I am a damned ubuntu
      shell: echo "I'm ubuntu"
